function showMessage(message: string): void {
  console.log(message);
}

function calc(num1: number, num2: number): number {
  return num1 + num2;
}

function customError(): never {
  throw new Error("Error");
}

const result = calc(1, 5);
showMessage("hello");
console.log(result);
customError();
